#!/usr/bin/env node
/**
 * Chooses the app an instance (and its Docker image) runs: writes shell/src/generated/app.ts
 * with the plugin's loader, its SQL migrations and changelogs, the secrets to create on first
 * start and the app's default environment.
 *
 *   node scripts/select-app.mjs pulse
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const id = process.argv[2] ?? process.env.APP;
const appFile = path.join(root, 'apps', id ?? '', 'app.json');
if (!id || !fs.existsSync(appFile)) {
  const known = fs.readdirSync(path.join(root, 'apps')).join(', ');
  console.error(`[select] Usage: node scripts/select-app.mjs <app>  (one of: ${known})`);
  process.exit(1);
}
const app = JSON.parse(fs.readFileSync(appFile, 'utf8'));
if (app.plugins.length !== 1) {
  console.error('[select] Instances with several plugins (Kitchen) are not supported yet.');
  process.exit(1);
}
const plugin = app.plugins[0];
const dir = path.join(root, 'vendor', 'plugins', plugin);
if (!fs.existsSync(dir)) {
  console.error(`[select] vendor/plugins/${plugin} is missing: run node scripts/sync.mjs first.`);
  process.exit(1);
}
const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));

const migrationsDir = path.join(dir, 'db', 'migrations');
const migrations = fs.existsSync(migrationsDir)
  ? fs
      .readdirSync(migrationsDir)
      .filter((f) => f.endsWith('.sql'))
      .sort()
      .map((f) => ({
        version: f.replace(/\.sql$/, ''),
        sql: fs.readFileSync(path.join(migrationsDir, f), 'utf8'),
      }))
  : [];

const changelogs = {};
for (const [locale, file] of [
  ['en', 'CHANGELOG.md'],
  ['de', 'CHANGELOG.de.md'],
  ['ro', 'CHANGELOG.ro.md'],
  ['hu', 'CHANGELOG.hu.md'],
]) {
  const p = path.join(dir, file);
  if (fs.existsSync(p)) changelogs[locale] = fs.readFileSync(p, 'utf8');
}

const out = `// AUTO-GENERATED by scripts/select-app.mjs (${id}) — DO NOT EDIT.
import type { PluginDefinition } from '@devquake/plugin-sdk';

export const APP = ${JSON.stringify(
  {
    id: app.id,
    name: app.name,
    tagline: app.tagline,
    plugin,
    version: pkg.version,
    hostedUrl: app.hostedUrl,
  },
  null,
  2,
)} as const;

export const loadPlugin = (): Promise<PluginDefinition> =>
  import(${JSON.stringify(pkg.name)}).then((m) => m.default as PluginDefinition);

/** Secrets created on first start when the environment does not set them. */
export const SECRETS: Record<string, 'base64-32' | 'hex-32'> = ${JSON.stringify(
  Object.fromEntries(Object.entries(app.secrets ?? {}).map(([name, s]) => [name, s.kind])),
)};

/** The app's defaults; the environment wins. */
export const DEFAULT_ENV: Record<string, string> = ${JSON.stringify(
  Object.fromEntries((app.env ?? []).map((v) => [v.name, v.default ?? ''])),
)};

export const MIGRATIONS: Array<{ version: string; sql: string }> = ${JSON.stringify(migrations)};

export const CHANGELOGS: Partial<Record<'en' | 'de' | 'ro' | 'hu', string>> = ${JSON.stringify(changelogs)};
`;
fs.mkdirSync(path.join(root, 'shell', 'src', 'generated'), { recursive: true });
fs.writeFileSync(path.join(root, 'shell', 'src', 'generated', 'app.ts'), out);
// Read by next.config.ts, which must not load the plugin itself.
fs.writeFileSync(
  path.join(root, 'shell', 'src', 'generated', 'plugin-package.ts'),
  `// AUTO-GENERATED by scripts/select-app.mjs — DO NOT EDIT.\nexport const PLUGIN_PACKAGE = ${JSON.stringify(pkg.name)};\n`,
);
console.log(`[select] ${app.name}: ${pkg.name} ${pkg.version}, ${migrations.length} migration(s).`);
