#!/usr/bin/env node
/**
 * Chooses the app an instance (and its Docker image) runs: writes shell/src/generated/app.ts with
 * each bundled plugin's loader, SQL migrations and changelogs, the secrets to create on first
 * start and the app's default environment. One plugin: served at the root of the instance. Several
 * (Household): each on its own hostname (ADR 0056 in DevQuake).
 *
 *   node scripts/select-app.mjs pulse
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const id = process.argv[2] ?? process.env.APP;
const appFile = path.join(root, 'apps', id ?? '', 'app.json');
if (!id || !fs.existsSync(appFile)) {
  const known = fs.readdirSync(path.join(root, 'apps')).join(', ');
  console.error(`[select] Usage: node scripts/select-app.mjs <app>  (one of: ${known})`);
  process.exit(1);
}
const app = JSON.parse(fs.readFileSync(appFile, 'utf8'));

const plugins = app.plugins.map((plugin) => {
  const dir = path.join(root, 'vendor', 'plugins', plugin);
  if (!fs.existsSync(dir)) {
    console.error(`[select] vendor/plugins/${plugin} is missing: run node scripts/sync.mjs first.`);
    process.exit(1);
  }
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
  const migrationsDir = path.join(dir, 'db', 'migrations');
  const migrations = fs.existsSync(migrationsDir)
    ? fs
        .readdirSync(migrationsDir)
        .filter((f) => f.endsWith('.sql'))
        .sort()
        .map((f) => ({
          version: f.replace(/\.sql$/, ''),
          sql: fs.readFileSync(path.join(migrationsDir, f), 'utf8'),
        }))
    : [];
  const changelogs = {};
  for (const [locale, file] of [
    ['en', 'CHANGELOG.md'],
    ['de', 'CHANGELOG.de.md'],
    ['ro', 'CHANGELOG.ro.md'],
    ['hu', 'CHANGELOG.hu.md'],
  ]) {
    const p = path.join(dir, file);
    if (fs.existsSync(p)) changelogs[locale] = fs.readFileSync(p, 'utf8');
  }
  return { id: plugin, pkg: pkg.name, version: pkg.version, migrations, changelogs };
});

const out = `// AUTO-GENERATED by scripts/select-app.mjs (${id}) — DO NOT EDIT.
import type { PluginDefinition } from '@devquake/plugin-sdk';

export const APP = ${JSON.stringify(
  {
    id: app.id,
    name: app.name,
    tagline: app.tagline,
    version: plugins.length === 1 ? plugins[0].version : (app.version ?? plugins[0].version),
    hostedUrl: app.hostedUrl,
    /** Several apps: each on its own hostname under the instance's domain (ADR 0056). */
    multi: plugins.length > 1,
  },
  null,
  2,
)} as const;

/** The bundled apps, in the order shown on the instance's home page. */
export const PLUGIN_IDS: readonly string[] = ${JSON.stringify(plugins.map((p) => p.id))};

const LOADERS: Record<string, () => Promise<PluginDefinition>> = {
${plugins
  .map(
    (p) =>
      `  ${JSON.stringify(p.id)}: () => import(${JSON.stringify(p.pkg)}).then((m) => m.default as PluginDefinition),`,
  )
  .join('\n')}
};

/** A bundled app's plugin; throws for an unknown id. */
export function loadPlugin(id: string = PLUGIN_IDS[0]!): Promise<PluginDefinition> {
  const load = LOADERS[id];
  if (!load) throw new Error(\`Unknown app "\${id}"\`);
  return load();
}

export const VERSIONS: Record<string, string> = ${JSON.stringify(
  Object.fromEntries(plugins.map((p) => [p.id, p.version])),
)};

/** Secrets created on first start when the environment does not set them. */
export const SECRETS: Record<string, 'base64-32' | 'hex-32'> = ${JSON.stringify(
  Object.fromEntries(Object.entries(app.secrets ?? {}).map(([name, s]) => [name, s.kind])),
)};

/** The app's defaults; the environment wins. */
export const DEFAULT_ENV: Record<string, string> = ${JSON.stringify(
  Object.fromEntries((app.env ?? []).map((v) => [v.name, v.default ?? ''])),
)};

export const MIGRATIONS: Record<string, Array<{ version: string; sql: string }>> = ${JSON.stringify(
  Object.fromEntries(plugins.map((p) => [p.id, p.migrations])),
)};

export const CHANGELOGS: Record<string, Partial<Record<'en' | 'de' | 'ro' | 'hu', string>>> = ${JSON.stringify(
  Object.fromEntries(plugins.map((p) => [p.id, p.changelogs])),
)};
`;
fs.mkdirSync(path.join(root, 'shell', 'src', 'generated'), { recursive: true });
fs.writeFileSync(path.join(root, 'shell', 'src', 'generated', 'app.ts'), out);
// Read by next.config.ts, which must not load the plugins themselves.
fs.writeFileSync(
  path.join(root, 'shell', 'src', 'generated', 'plugin-package.ts'),
  `// AUTO-GENERATED by scripts/select-app.mjs — DO NOT EDIT.\nexport const PLUGIN_PACKAGES: string[] = ${JSON.stringify(plugins.map((p) => p.pkg))};\n`,
);
console.log(
  `[select] ${app.name}: ${plugins.map((p) => `${p.pkg} ${p.version}`).join(', ')} (${plugins.reduce((n, p) => n + p.migrations.length, 0)} migration(s)).`,
);
